version: '3'

services:
  apache_server:
    image: httpd:latest
    container_name: apache_server
    platform: linux/amd64
    ports:
      - "80:80"
    volumes:
      - ./apache/ican.com:/usr/local/apache2/htdocs/ican.com
      - ./apache/ucan.com:/usr/local/apache2/htdocs/ucan.com
      - ./apache/conf:/usr/local/apache2/conf/vhosts
    command: >
      bash -c "echo 'IncludeOptional conf/vhosts/*.conf' >> /usr/local/apache2/conf/httpd.conf &&
               httpd-foreground"

  ftp_ican:
    image: fauria/vsftpd
    platform: linux/amd64
    container_name: ftp_ican
    ports:
      - "2121:21"
      - "21100-21110:21100-21110"
    volumes:
      - ./apache/ican.com:/home/vsftpd
    environment:
      - FTP_USER=ican.com
      - FTP_PASS=123456
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
      - ANON_UPLOAD_ENABLE=NO

  ftp_ucan:
    image: fauria/vsftpd
    platform: linux/amd64
    container_name: ftp_ucan
    ports:
      - "2221:21"
    volumes:
      - ./apache/ucan.com:/home/vsftpd
    environment:
      - FTP_USER=ucan.com
      - FTP_PASS=123456
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21200
      - PASV_MAX_PORT=21210
      - ANON_UPLOAD_ENABLE=NO
